[package]
name = "rhai-rusp"
version = "0.95.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
rhai = { workspace = true }
rusp-lib = { workspace = true }
anyhow = { workspace = true }
quick-protobuf = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
